version: '3.8'
services:
  dev:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: /bin/sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
