# If this name is changed, "release-02-publish-to-npm.yml" needs to be adapted!
name: Build the package and create the release within GitHub

on:
  push:
    tags:
      - 'v*'

jobs:
  
  # ToDo
  #build:
  
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitMode: true
          failOnError: true
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n\n#{{UNCATEGORIZED}}\n</details>",
              "pr_template": "- #{{TITLE}}",
            }
      - uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          # ToDo remove with v1.0.0
          prerelease: true
          # ToDo do we need / want this?
          #artifacts: "release.tar.gz,foo/*.txt"
          body: ${{steps.build_changelog.outputs.changelog}}
          