name: Build the package and create the release within GitHub

on:
  push:
    tags:
      - 'v*'

jobs:
  
  # ToDo
  #build:
  
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          # ToDo remove with v1.0.0
          prerelease: true
          # ToDo do we need / want this?
          #artifacts: "release.tar.gz,foo/*.txt"
          # ToDo nice changelog
          